apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-ui-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-ui
      version: v1
  template:
    metadata:
      labels:
        app: expense-ui
        version: v1
    spec:
      containers:
        - name: expense-ui
          image: "raghultamilaiah/expense-ui"